modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory (24 is current forge version)
[[mods]] #mandatory

modId="esotericacraft" #mandatory
version="${3.1}" #mandatory
displayName="EsotericaCraft" #mandatory

description='''
Necessary to have the best possible Esoterica server experience
'''